### ISSUE TITLE
Broken using Node v18.16.0 & v20.13.1

### ISSUE THREAD

**Issue by mrienstra** [pqina/pintura-example-react-typescript#1]
I didn't have any issue with https://github.com/pqina/pintura-example-nextjs and https://github.com/pqina/pintura-example-react , both were easy to get running locally.

But with this repo, I see "undefined" instead of some of the plugin names (buttons down the left side), and attempting to open the last tool -- presumably "Redact" -- throws an error:

```
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'filter')
TypeError: Cannot read properties of undefined (reading 'filter')
    at e.$$.update (http://localhost:3000/static/js/bundle.js:86004:7)
    at ga (http://localhost:3000/static/js/bundle.js:61730:14)
    at new ab.util.duration (http://localhost:3000/static/js/bundle.js:86021:16)
    at xr (http://localhost:3000/static/js/bundle.js:61395:10)
    at Zc (http://localhost:3000/static/js/bundle.js:66095:20)
    at Xc (http://localhost:3000/static/js/bundle.js:66130:17)
    at ga (http://localhost:3000/static/js/bundle.js:61730:73)
    at new qc (http://localhost:3000/static/js/bundle.js:66243:14)
    at Array.Xh (http://localhost:3000/static/js/bundle.js:70645:71)
    at Vn (http://localhost:3000/static/js/bundle.js:61225:16)
```

![localhost_3000_ (11)](https://github.com/pqina/pintura-example-react-typescript/assets/669326/de1231c0-d589-48a9-a51f-5ccc5beea11a)
![localhost_3000_ (12)](https://github.com/pqina/pintura-example-react-typescript/assets/669326/1d953191-65c5-441e-9e66-ac2842b859a8)

It was also a little hard to find this repo, a few of the other repos link to it -- see https://github.com/search?q=org%3Apqina%20pintura-example-react-typescript&type=code -- but others do not, and https://pqina.nl/pintura/guide/#examples-panel does not.

---

Also, it would be nice if all of these example repos had GitHub issues enabled. I also found a (minor) issue with https://github.com/pqina/pintura-example-nextjs (sticker SVGs are missing), but I can't open an issue there. I'd much prefer to give feedback on GitHub repos in the repo itself, rather than figuring out how best to contact PQINA.

**Comment by rikschennink** [comment]
Weird it seems to run without issues on Stackblitz, I'll run some tests on Monday.

> Also, it would be nice if all of these example repos had GitHub issues enabled. I also found a (minor) issue with https://github.com/pqina/pintura-example-nextjs (sticker SVGs are missing), but I can't open an issue there. I'd much prefer to give feedback on GitHub repos in the repo itself, rather than figuring out how best to contact PQINA.

I'll open up the issue trackers.

**Comment by rikschennink** [comment]
The issue was that it tried to load all plugins instead of only the ones that had their locale loaded. Just fixed.

**Comment by rikschennink** [comment]
Added link from react repo to this one
